#!/usr/bin/env python
import sys
import re
import warnings
from pathlib import Path

warnings.filterwarnings("ignore", category=SyntaxWarning, module="pysbd")

PIPELINE_DATA = Path(__file__).resolve().parent.parent.parent.parent / "pipeline_data"


def markdown_to_docx(md_path: str, docx_path: str):
    """Convert a markdown SRS file to a formatted Word document."""
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    md_text = Path(md_path).read_text(encoding="utf-8")
    doc = Document()

    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    doc.add_paragraph()
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run('Software Requirement Specification (SRS)')
    run.bold = True
    run.font.size = Pt(26)
    run.font.color.rgb = RGBColor(0, 51, 102)

    doc.add_paragraph()
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run('Generated by AI Software Factory Pipeline')
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(100, 100, 100)

    doc.add_page_break()

    in_code_block = False
    code_lines = []

    for line in md_text.split('\n'):
        stripped = line.strip()

        if stripped.startswith('```'):
            if in_code_block:
                code_para = doc.add_paragraph()
                code_run = code_para.add_run('\n'.join(code_lines))
                code_run.font.name = 'Courier New'
                code_run.font.size = Pt(9)
                code_para.paragraph_format.left_indent = Inches(0.5)
                code_lines = []
                in_code_block = False
            else:
                in_code_block = True
            continue

        if in_code_block:
            code_lines.append(line)
            continue

        if stripped.startswith('# '):
            doc.add_heading(stripped[2:], level=1)
        elif stripped.startswith('## '):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith('### '):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith('#### '):
            doc.add_heading(stripped[5:], level=4)
        elif stripped.startswith('|') and not all(c in '|-: ' for c in stripped):
            cells = [c.strip() for c in stripped.split('|')[1:-1]]
            para = doc.add_paragraph()
            para.paragraph_format.left_indent = Inches(0.3)
            para.add_run('  |  '.join(cells)).font.size = Pt(10)
        elif stripped.startswith('|') and all(c in '|-: ' for c in stripped):
            continue
        elif stripped.startswith('- ') or stripped.startswith('* '):
            doc.add_paragraph(stripped[2:], style='List Bullet')
        elif re.match(r'^\d+\.\s', stripped):
            text = re.sub(r'^\d+\.\s', '', stripped)
            doc.add_paragraph(text, style='List Number')
        elif stripped.startswith('**') and stripped.endswith('**'):
            para = doc.add_paragraph()
            run = para.add_run(stripped.strip('*'))
            run.bold = True
        elif not stripped:
            continue
        else:
            doc.add_paragraph(stripped)

    doc.save(docx_path)
    print(f"\n✅ SRS Word document saved to: {docx_path}")


def run():
    from step01_requirements.crew import Step01Requirements

    print("=" * 60)
    print("  STEP 01 - REQUIREMENTS ANALYSIS")
    print("  Generates IEEE 830 SRS Document")
    print("=" * 60)

    project_idea = input("\n📝 Enter your project idea:\n> ").strip()
    if not project_idea:
        print("❌ No project idea provided. Exiting.")
        sys.exit(1)

    PIPELINE_DATA.mkdir(parents=True, exist_ok=True)

    # Save the project idea for reference by later steps
    (PIPELINE_DATA / "00_project_idea.txt").write_text(project_idea, encoding="utf-8")

    inputs = {'project_idea': project_idea}

    while True:
        print("\n🚀 Running requirements analysis...\n")
        result = Step01Requirements().crew().kickoff(inputs=inputs)

        # Write output to pipeline_data
        srs_md = PIPELINE_DATA / "01_srs.md"
        srs_md.write_text(str(result), encoding="utf-8")

        # Generate Word document
        srs_docx = PIPELINE_DATA / "01_srs.docx"
        if srs_md.exists():
            markdown_to_docx(str(srs_md), str(srs_docx))
            import subprocess, platform
            if platform.system() == 'Darwin':
                subprocess.run(['open', str(srs_docx.resolve())])

        print("\n" + "=" * 60)
        print("✅ Step 01 Complete!")
        print(f"   SRS (MD):   {srs_md}")
        print(f"   SRS (DOCX): {srs_docx}")
        print("=" * 60)

        choice = input("\n🔍 Review the output. Press Enter to proceed to Step 02, or 'r' to re-run: ").strip().lower()
        if choice != 'r':
            print("\n✅ Step 01 approved. Run step02_architecture next.")
            break
        print("\n🔄 Re-running Step 01...")
